// Sample data for initialization
import { Table, MenuItem, Customer, Coupon } from '../types';

export const sampleTables: Table[] = [
  { id: '1', number: 1, seats: 2, status: 'available' },
  { id: '2', number: 2, seats: 4, status: 'available' },
  { id: '3', number: 3, seats: 4, status: 'available' },
  { id: '4', number: 4, seats: 6, status: 'available' },
  { id: '5', number: 5, seats: 2, status: 'available' },
  { id: '6', number: 6, seats: 4, status: 'available' },
  { id: '7', number: 7, seats: 8, status: 'available' },
  { id: '8', number: 8, seats: 2, status: 'available' },
  { id: '9', number: 9, seats: 4, status: 'available' },
  { id: '10', number: 10, seats: 6, status: 'available' },
];

export const sampleMenuItems: MenuItem[] = [
  // Veg Items
  {
    id: 'm1',
    name: 'Paneer Tikka',
    category: 'veg',
    price: 220,
    image: '🧀',
    description: 'Grilled cottage cheese with Indian spices',
    available: true,
    isPopular: true,
  },
  {
    id: 'm2',
    name: 'Veg Biryani',
    category: 'veg',
    price: 180,
    image: '🍚',
    description: 'Aromatic basmati rice with mixed vegetables',
    available: true,
    isPopular: true,
  },
  {
    id: 'm3',
    name: 'Dal Makhani',
    category: 'veg',
    price: 160,
    image: '🍛',
    description: 'Creamy black lentils cooked overnight',
    available: true,
  },
  {
    id: 'm4',
    name: 'Mushroom Masala',
    category: 'veg',
    price: 190,
    image: '🍄',
    description: 'Fresh mushrooms in rich tomato gravy',
    available: true,
  },
  {
    id: 'm5',
    name: 'Veg Manchurian',
    category: 'veg',
    price: 150,
    image: '🥟',
    description: 'Indo-Chinese vegetable balls in spicy sauce',
    available: true,
  },
  
  // Non-Veg Items
  {
    id: 'm6',
    name: 'Butter Chicken',
    category: 'non-veg',
    price: 280,
    image: '🍗',
    description: 'Tender chicken in creamy tomato sauce',
    available: true,
    isPopular: true,
  },
  {
    id: 'm7',
    name: 'Chicken Biryani',
    category: 'non-veg',
    price: 250,
    image: '🍛',
    description: 'Fragrant rice layered with succulent chicken',
    available: true,
    isPopular: true,
  },
  {
    id: 'm8',
    name: 'Fish Tikka',
    category: 'non-veg',
    price: 320,
    image: '🐟',
    description: 'Marinated fish grilled to perfection',
    available: true,
  },
  {
    id: 'm9',
    name: 'Mutton Rogan Josh',
    category: 'non-veg',
    price: 350,
    image: '🍖',
    description: 'Kashmiri style mutton curry',
    available: true,
  },
  {
    id: 'm10',
    name: 'Chicken Kebab',
    category: 'non-veg',
    price: 240,
    image: '🍢',
    description: 'Spicy grilled chicken skewers',
    available: true,
  },

  // Drinks
  {
    id: 'm11',
    name: 'Fresh Lime Soda',
    category: 'drinks',
    price: 60,
    image: '🍋',
    description: 'Refreshing lime with soda',
    available: true,
  },
  {
    id: 'm12',
    name: 'Mango Lassi',
    category: 'drinks',
    price: 80,
    image: '🥭',
    description: 'Creamy yogurt drink with mango',
    available: true,
    isPopular: true,
  },
  {
    id: 'm13',
    name: 'Cold Coffee',
    category: 'drinks',
    price: 100,
    image: '☕',
    description: 'Chilled coffee with ice cream',
    available: true,
  },
  {
    id: 'm14',
    name: 'Virgin Mojito',
    category: 'drinks',
    price: 120,
    image: '🍹',
    description: 'Mint and lime refresher',
    available: true,
  },
  {
    id: 'm15',
    name: 'Masala Chai',
    category: 'drinks',
    price: 40,
    image: '🍵',
    description: 'Traditional Indian spiced tea',
    available: true,
  },

  // Hookah
  {
    id: 'm16',
    name: 'Double Apple Hookah',
    category: 'hookah',
    price: 400,
    image: '💨',
    description: 'Classic double apple flavor',
    available: true,
  },
  {
    id: 'm17',
    name: 'Blueberry Hookah',
    category: 'hookah',
    price: 450,
    image: '💨',
    description: 'Sweet blueberry flavor',
    available: true,
  },
  {
    id: 'm18',
    name: 'Mint Hookah',
    category: 'hookah',
    price: 400,
    image: '💨',
    description: 'Refreshing mint flavor',
    available: true,
  },

  // Desserts
  {
    id: 'm19',
    name: 'Gulab Jamun',
    category: 'dessert',
    price: 80,
    image: '🍯',
    description: 'Sweet milk dumplings in sugar syrup',
    available: true,
  },
  {
    id: 'm20',
    name: 'Ice Cream Sundae',
    category: 'dessert',
    price: 120,
    image: '🍨',
    description: 'Vanilla ice cream with toppings',
    available: true,
  },
];

export const sampleCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'Rajesh Kumar',
    phone: '+91 9876543210',
    email: 'rajesh@example.com',
    birthday: '1990-05-15',
    totalVisits: 25,
    totalSpent: 12500,
    loyaltyPoints: 1250,
    favoriteItems: ['m6', 'm7'],
    lastVisit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    name: 'Priya Sharma',
    phone: '+91 9876543211',
    email: 'priya@example.com',
    birthday: '1995-08-22',
    totalVisits: 18,
    totalSpent: 9200,
    loyaltyPoints: 920,
    favoriteItems: ['m1', 'm2', 'm12'],
    lastVisit: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    name: 'Amit Singh',
    phone: '+91 9876543212',
    totalVisits: 10,
    totalSpent: 5800,
    loyaltyPoints: 580,
    favoriteItems: ['m16', 'm17'],
    lastVisit: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const sampleCoupons: Coupon[] = [
  {
    id: 'cp1',
    code: 'WELCOME50',
    description: 'Welcome offer - Flat 50 off',
    discountType: 'fixed',
    discountValue: 50,
    minOrderValue: 300,
    validFrom: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    validUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    usageLimit: 100,
    usedCount: 23,
    active: true,
  },
  {
    id: 'cp2',
    code: 'FEAST20',
    description: '20% off on orders above 500',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 500,
    maxDiscount: 150,
    validFrom: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    validUntil: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    usageLimit: 50,
    usedCount: 12,
    active: true,
  },
];
